
import WaitingPopup from "./WaitingPopup";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
      < >
          {children}
          <WaitingPopup/>
      </>

  );
}
